### ISSUE TITLE
RateLimitError

### ISSUE THREAD

**Issue by thisisowenlo** [sean1832/SumGPT#11]
每次執行的結果都是出現

openai.error.RateLimitError: This app has encountered an error. The original error message is redacted to prevent data leaks. Full error details have been recorded in the logs (if you're on Streamlit Cloud, click on 'Manage app' in the lower right of your app).

**Comment by sean1832** [comment]
你好，请问你用的API是免费试用 (free trial) 的还是pay as you go的？

根据[openAI的官网资料](https://platform.openai.com/docs/guides/rate-limits/overview)，免费试用的API，一分钟只能呼叫20次API，也就是说，你的最大区块值（chunk）不能超过20。而对于付费（pay as you go）的API，一分钟可以呼叫3500次。所以，如果是使用的免费试用API，请将区块值调到20个以下，或者你可以选择切换付费API方案。

**Comment by thisisowenlo** [comment]
我使用的是 free API
input 的 youtube link：https://www.youtube.com/watch?v=j527pvg8cIM&t=9&ab_channel=PROOF

系統給出的 Chunks 是 4
而我也在 Advanced Options 將 Delay 打開了，還是得到同樣的錯誤訊息

**Comment by sean1832** [comment]
hum...
我这里测试并没有什么问题。
![image](https://user-images.githubusercontent.com/84948038/229808408-05794e65-0ae5-47b4-a984-f469fa0c3382.png)

你可以依次尝试以下：
1. 进入openAI[检查试用余额](https://platform.openai.com/account/usage)
2. 下载[本地版SumGPT](https://github.com/sean1832/SumGPT/archive/refs/tags/1.0.5.zip)，下载好之后，确保你安装了python，然后双击运行`RUN.bat`。如果还有报错，请把错误信息发上来。因为网页版是不会报详细的错误信息的。

**Comment by thisisowenlo** [comment]
下載後將 .bat 改寫為 .sh 後在本地端 Mac 將代碼運行起來，看了錯誤訊息發現是我的 free trial 過期了，感謝！
