### ISSUE TITLE
[FEATURE] Support Chinese caption video

### ISSUE THREAD

**Issue by thisisowenlo** [sean1832/SumGPT#15]
I tried to summarize a youtube video with Chinese (traditional) subtitles and it tells me the following message：

```
❌ Caption language currently not supported.

{'zh-TW': <Caption lang="Chinese (Taiwan)" code="zh-TW">}

```
**Describe the solution you'd like**

Would like to request a feature to support this kind of video.

**Comment by sean1832** [comment]
Hello, could you please share the YouTube link as a reference? Thank you.

**Comment by thisisowenlo** [comment]
Hi,

This is the video link I tried to summarize: https://www.youtube.com/watch?v=7VdhEE194fc

Thanks!
